module.exports = {
  prefix: '',
  important: false,
  separator: ':',
  theme: {
    screens: {
      sm: '576px',
      md: '768px',
      lg: '1024px',
      xl: '1441px',
    },
    colors: {
      transparent: 'transparent',
      black: '#22292f',
      white: '#fff',
      'grey-light': '#f9f8fa',
      dark: '#4C566A',
      red: '#BF616A'
    },
    spacing: {
      px: '1px',
      '0': '0',
      '1': '0.25rem',
      '2': '0.5rem',
      '3': '0.75rem',
      '4': '1rem',
      '5': '1.25rem',
      '6': '1.5rem',
      '8': '2rem',
      '10': '2.5rem',
      '12': '3rem',
      '16': '4rem',
      '20': '5rem',
      '24': '6rem',
      '32': '8rem',
      '40': '10rem',
      '48': '12rem',
      '56': '14rem',
      '64': '16rem',
    },
    backgroundColor: theme => theme('colors'),
    backgroundPosition: {
      bottom: 'bottom',
      center: 'center',
      left: 'left',
    //   'left-bottom': 'left bottom',
    //   'left-top': 'left top',
      right: 'right',
    //   'right-bottom': 'right bottom',
    //   'right-top': 'right top',
      top: 'top',
    },
    backgroundSize: {
      auto: 'auto',
      cover: 'cover',
      contain: 'contain',
    },
    borderColor: theme => ({
      ...theme('colors'),
      default: theme('colors.gray.300', 'currentColor'),
    }),
    // borderRadius: {
    //   none: '0',
    //   sm: '0.125rem',
    //   default: '0.25rem',
    //   lg: '0.5rem',
    //   full: '9999px',
    // },
    borderWidth: {
      default: '1px',
      '0': '0',
      '2': '2px',
    //   '4': '4px',
    //   '8': '8px',
    },
    boxShadow: {
      default: '0 1px 3px 0 rgba(0, 0, 0, 0.1), 0 1px 2px 0 rgba(0, 0, 0, 0.06)',
      md: '0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -1px rgba(0, 0, 0, 0.06)',
      lg: '0 10px 15px -3px rgba(0, 0, 0, 0.1), 0 4px 6px -2px rgba(0, 0, 0, 0.05)',
      xl: '0 20px 25px -5px rgba(0, 0, 0, 0.1), 0 10px 10px -5px rgba(0, 0, 0, 0.04)',
      '2xl': '0 25px 50px -12px rgba(0, 0, 0, 0.25)',
    //   inner: 'inset 0 2px 4px 0 rgba(0, 0, 0, 0.06)',
    //   outline: '0 0 0 3px rgba(66, 153, 225, 0.5)',
      none: 'none',
    },
    // container: {},
    // cursor: {
    //   auto: 'auto',
    //   default: 'default',
    //   pointer: 'pointer',
    //   wait: 'wait',
    //   text: 'text',
    //   move: 'move',
    //   'not-allowed': 'not-allowed',
    // },
    fill: {
      current: 'currentColor',
    },
    flex: {
      '1': '1 1 0%',
      auto: '1 1 auto',
      initial: '0 1 auto',
      none: 'none',
    },
    flexGrow: {
      '0': '0',
      default: '1',
    },
    flexShrink: {
      '0': '0',
      default: '1',
    },
    fontFamily: {
      sans: [
        '-apple-system',
        'BlinkMacSystemFont',
        '"Segoe UI"',
        'Roboto',
        '"Helvetica Neue"',
        'Arial',
        '"Noto Sans"',
        'sans-serif',
        '"Apple Color Emoji"',
        '"Segoe UI Emoji"',
        '"Segoe UI Symbol"',
        '"Noto Color Emoji"',
      ],
      serif: [
        'Georgia',
        'Cambria',
        '"Times New Roman"',
        'Times',
        'serif',
      ],
      mono: [
        'Menlo',
        'Monaco',
        'Consolas',
        '"Liberation Mono"',
        '"Courier New"',
        'monospace',
      ],
    },
    fontSize: {
      'ultra-xs': '0.625rem',
      xs: '0.75rem',
      sm: '0.875em',
      base: '1rem',
      lg: '1.125rem',
      xl: '1.25rem',
      '2xl': '1.5625rem',
      '3xl': '1.875rem',
      '4xl': '2.1875rem',
      '5xl': '2.5rem',
    },
    fontWeight: {
    //   hairline: '100',
    //   thin: '200',
    light: '300',
    normal: '400',
    //   medium: '500',
    //   semibold: '600',
    bold: '700',
    //   extrabold: '800',
    //   black: '900',
    },
    height: theme => ({
      auto: 'auto',
      ...theme('spacing'),
      full: '100%',
      screen: '100vh',
    }),
    // inset: {
    //   '0': '0',
    //   auto: 'auto',
    // },
    letterSpacing: {
      tighter: '-0.05em',
      tight: '-0.025em',
      normal: '0',
      wide: '0.025em',
      wider: '0.05em',
      widest: '0.1em',
    },
    // lineHeight: {
    //   none: '1',
    //   tight: '1.25',
    //   snug: '1.375',
    //   normal: '1.5',
    //   relaxed: '1.625',
    //   loose: '2',
    // },
    listStyleType: {
      none: 'none',
      disc: 'disc',
      decimal: 'decimal',
    },
    margin: (theme, { negative }) => ({
      auto: 'auto',
      ...theme('spacing'),
      ...negative(theme('spacing')),
    }),
    // maxHeight: {
    //   full: '100%',
    //   screen: '100vh',
    // },
    // maxWidth: {
    //   xs: '20rem',
    //   sm: '24rem',
    //   md: '28rem',
    //   lg: '32rem',
    //   xl: '36rem',
    //   '2xl': '42rem',
    //   '3xl': '48rem',
    //   '4xl': '56rem',
    //   '5xl': '64rem',
    //   '6xl': '72rem',
    //   full: '100%',
    // },
    // minHeight: {
    //   '0': '0',
    //   full: '100%',
    //   screen: '100vh',
    // },
    // minWidth: {
    //   '0': '0',
    //   full: '100%',
    // },
    objectPosition: {
      bottom: 'bottom',
      center: 'center',
      left: 'left',
    //   'left-bottom': 'left bottom',
    //   'left-top': 'left top',
      right: 'right',
    //   'right-bottom': 'right bottom',
    //   'right-top': 'right top',
      top: 'top',
    },
    // opacity: {
    //   '0': '0',
    //   '25': '0.25',
    //   '50': '0.5',
    //   '75': '0.75',
    //   '100': '1',
    // },
    order: {
      first: '-9999',
      last: '9999',
      none: '0',
      '1': '1',
      '2': '2',
      '3': '3',
      '4': '4',
      // '5': '5',
      // '6': '6',
    //   '7': '7',
    //   '8': '8',
    //   '9': '9',
    //   '10': '10',
    //   '11': '11',
    //   '12': '12',
    },
    padding: theme => theme('spacing'),
    // stroke: {
    //   current: 'currentColor',
    // },
    textColor: theme => theme('colors'),
    width: theme => ({
      auto: 'auto',
      ...theme('spacing'),
      '1/2': '50%',
      '1/3': '33.333333%',
      '2/3': '66.666667%',
      '1/4': '25%',
      '3/4': '75%',
      // '1/5': '20%',
      '2/5': '40%',
      '3/5': '60%',
      '4/5': '80%',
      // '1/6': '16.666667%',
      '5/6': '83.333333%',
      // '1/12': '8.333333%',
      // '5/12': '41.666667%',
      // '7/12': '58.333333%',
      // '11/12': '91.666667%',
      full: '100%',
      screen: '100vw',
    }),
    // zIndex: {
    //   auto: 'auto',
    //   '0': '0',
    //   '10': '10',
    //   '20': '20',
    //   '30': '30',
    //   '40': '40',
    //   '50': '50',
    // },
  },
  variants: {
    alignContent: ['responsive'],
    alignItems: ['responsive'],
    alignSelf: ['responsive'],
    backgroundColor: ['hover'],
    backgroundPosition: [],
    backgroundRepeat: [],
    backgroundSize: [],
    borderColor: [],
    borderRadius: [],
    borderStyle: [],
    borderWidth: [],
    boxShadow: ['hover','responsive'],
    cursor: [],
    display: ['responsive'],
    flex: ['responsive'],
    flexDirection: ['responsive'],
    flexGrow: ['responsive'],
    flexShrink: ['responsive'],
    flexWrap: ['responsive'],
    fontSize: [],
    fontStyle: ['hover'],
    fontWeight: [],
    height: [],
    inset: [],
    justifyContent: ['responsive'],
    letterSpacing: ['responsive'],
    listStyleType: [],
    margin: ['responsive'],
    objectFit: [],
    objectPosition: [],
    opacity: ['hover'],
    order: ['responsive'],
    padding: ['responsive'],
    position: [],
    textAlign: ['responsive'],
    textColor: ['hover'],
    textDecoration: ['hover'],
    textTransform: [],
    width: ['responsive'],
  },
  corePlugins: {
    accessibility: false,
    appearance: false,
    backgroundAttachment: false,
    borderCollapse: false,
    fill: false,
    float: false,
    fontFamily: false,
    fontSmoothing: false,
    lineHeight: false,
    listStylePosition: false,
    maxHeight: false,
    maxWidth: false,
    minHeight: false,
    minWidth: false,
    outline: false,
    overflow: false,
    pointerEvents: false,
    resize: false,
    stroke: false,
    tableLayout: false,
    userSelect: false,
    verticalAlign: false,
    visibility: false,
    whitespace: false,
    wordBreak: false,
    zIndex: false,
  },
  plugins: [],
}